version: "3.9"

services:
    app:
        build: .
        container_name: master-rents
        volumes:
            - .:/usr/src/app
        ports:
            - 8080:8080
        command: npm run dev